[server]
runOnSave = false
fileWatcherType = "none"
maxUploadSize = 200
enableXsrfProtection = false

[runner]
fastReruns = true
magicEnabled = false

[browser]
gatherUsageStats = false

[theme]
base = "light"

[client]
showErrorDetails = false 